# Generated by Django 4.0.6 on 2022-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date_of_buy', models.DateTimeField()),
                ('alloted', models.CharField(default='Random', max_length=50)),
                ('room', models.CharField(default='Random', max_length=50)),
            ],
        ),
    ]
