# Generated by Django 4.0.6 on 2022-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tender_no',
            field=models.IntegerField(default=0),
        ),
    ]
