# Generated by Django 4.0.6 on 2022-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_tender_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='tender_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
